
version: '3'

services:
  postgres:
    image: postgis/postgis:14-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgeres
      POSTGRES_PASSWORD: postgeres
      POSTGRES_DB: postgeres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: