"""initial migration from django models

Revision ID: abedaa0747a0
Revises: 
Create Date: 2023-12-23 21:19:37.271668

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'abedaa0747a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('oauth2_provider_accesstoken_application_id_b22886e1', table_name='oauth2_provider_accesstoken')
    op.drop_index('oauth2_provider_accesstoken_token_8af090f8_like', table_name='oauth2_provider_accesstoken')
    op.drop_index('oauth2_provider_accesstoken_user_id_6e4c9a65', table_name='oauth2_provider_accesstoken')
    op.drop_table('oauth2_provider_accesstoken')
    op.drop_table('temp_business_movo')
    op.drop_table('django_migrations')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('oauth2_provider_refreshtoken_application_id_2d1c311b', table_name='oauth2_provider_refreshtoken')
    op.drop_index('oauth2_provider_refreshtoken_user_id_da837fce', table_name='oauth2_provider_refreshtoken')
    op.drop_table('oauth2_provider_refreshtoken')
    op.drop_table('socialaccount_socialapp')
    op.drop_table('layer')
    op.drop_index('oauth2_provider_application_client_id_03f0cc84_like', table_name='oauth2_provider_application')
    op.drop_index('oauth2_provider_application_client_secret_53133678', table_name='oauth2_provider_application')
    op.drop_index('oauth2_provider_application_client_secret_53133678_like', table_name='oauth2_provider_application')
    op.drop_index('oauth2_provider_application_user_id_79829054', table_name='oauth2_provider_application')
    op.drop_table('oauth2_provider_application')
    op.drop_index('socialaccount_socialapp_sites_site_id_2579dee5', table_name='socialaccount_socialapp_sites')
    op.drop_index('socialaccount_socialapp_sites_socialapp_id_97fb6e7d', table_name='socialaccount_socialapp_sites')
    op.drop_table('socialaccount_socialapp_sites')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_table('social_auth_nonce')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_table('topology')
    op.drop_table('social_auth_association')
    op.drop_index('django_site_domain_a2e37b91_like', table_name='django_site')
    op.drop_table('django_site')
    op.drop_index('social_auth_usersocialauth_uid_796e51dc', table_name='social_auth_usersocialauth')
    op.drop_index('social_auth_usersocialauth_uid_796e51dc_like', table_name='social_auth_usersocialauth')
    op.drop_index('social_auth_usersocialauth_user_id_17d28448', table_name='social_auth_usersocialauth')
    op.drop_table('social_auth_usersocialauth')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index('oauth2_provider_idtoken_application_id_08c5ff4f', table_name='oauth2_provider_idtoken')
    op.drop_index('oauth2_provider_idtoken_user_id_dd512b59', table_name='oauth2_provider_idtoken')
    op.drop_table('oauth2_provider_idtoken')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_table('temp_business')
    op.drop_table('spatial_ref_sys')
    op.drop_index('socialaccount_socialtoken_account_id_951f210e', table_name='socialaccount_socialtoken')
    op.drop_index('socialaccount_socialtoken_app_id_636a42d7', table_name='socialaccount_socialtoken')
    op.drop_table('socialaccount_socialtoken')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_table('django_content_type')
    op.drop_index('social_auth_code_code_a2393167', table_name='social_auth_code')
    op.drop_index('social_auth_code_code_a2393167_like', table_name='social_auth_code')
    op.drop_index('social_auth_code_timestamp_176b341f', table_name='social_auth_code')
    op.drop_table('social_auth_code')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index('account_emailaddress_email_03be32b2_like', table_name='account_emailaddress')
    op.drop_index('account_emailaddress_user_id_2c513194', table_name='account_emailaddress')
    op.drop_table('account_emailaddress')
    op.drop_index('social_auth_partial_timestamp_50f2119f', table_name='social_auth_partial')
    op.drop_index('social_auth_partial_token_3017fea3', table_name='social_auth_partial')
    op.drop_index('social_auth_partial_token_3017fea3_like', table_name='social_auth_partial')
    op.drop_table('social_auth_partial')
    op.drop_index('oauth2_provider_grant_application_id_81923564', table_name='oauth2_provider_grant')
    op.drop_index('oauth2_provider_grant_code_49ab4ddf_like', table_name='oauth2_provider_grant')
    op.drop_index('oauth2_provider_grant_user_id_e8f62af8', table_name='oauth2_provider_grant')
    op.drop_table('oauth2_provider_grant')
    op.drop_index('account_emailconfirmation_email_address_id_5b7f8c58', table_name='account_emailconfirmation')
    op.drop_index('account_emailconfirmation_key_f43612bd_like', table_name='account_emailconfirmation')
    op.drop_table('account_emailconfirmation')
    op.drop_index('socialaccount_socialaccount_user_id_8146e70c', table_name='socialaccount_socialaccount')
    op.drop_table('socialaccount_socialaccount')
    op.alter_column('business', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business', 'address_line1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('business', 'address_line2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('business', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_business_location', 'business', ['location'], unique=False, postgresql_using='gist')
    op.alter_column('business_categories', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business_categories', 'business_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('business_categories', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_businesscategories_business_id_e4b002d4', table_name='business_categories')
    op.drop_index('ba7besh_businesscategories_category_id_535d71ee', table_name='business_categories')
    op.drop_constraint('ba7besh_businesscate_category_id_535d71ee_fk_ba7besh_c', 'business_categories', type_='foreignkey')
    op.drop_constraint('ba7besh_businesscate_business_id_e4b002d4_fk_ba7besh_b', 'business_categories', type_='foreignkey')
    op.create_foreign_key(None, 'business_categories', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'business_categories', 'category', ['category_id'], ['id'], ondelete='PROTECT')
    op.alter_column('business_contacts', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business_contacts', 'business_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_businesscontacts_business_id_15cf0080', table_name='business_contacts')
    op.drop_constraint('ba7besh_businesscont_business_id_15cf0080_fk_ba7besh_b', 'business_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'business_contacts', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('business_features', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business_features', 'business_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('business_features', 'feature_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_businessfeatures_business_id_14cddcb8', table_name='business_features')
    op.drop_index('ba7besh_businessfeatures_feature_id_bc4dac42', table_name='business_features')
    op.drop_constraint('ba7besh_businessfeat_business_id_14cddcb8_fk_ba7besh_b', 'business_features', type_='foreignkey')
    op.drop_constraint('ba7besh_businessfeat_feature_id_bc4dac42_fk_ba7besh_f', 'business_features', type_='foreignkey')
    op.create_foreign_key(None, 'business_features', 'feature', ['feature_id'], ['id'], ondelete='PROTECT')
    op.create_foreign_key(None, 'business_features', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('business_tags', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business_tags', 'business_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_businesstags_business_id_cb68436c', table_name='business_tags')
    op.drop_constraint('ba7besh_businesstags_business_id_cb68436c_fk_ba7besh_b', 'business_tags', type_='foreignkey')
    op.create_foreign_key(None, 'business_tags', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('business_working_hours', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('business_working_hours', 'business_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_businessworkinghours_business_id_8a81eaf1', table_name='business_working_hours')
    op.drop_constraint('unique_business_day', 'business_working_hours', type_='unique')
    op.drop_constraint('ba7besh_businesswork_business_id_8a81eaf1_fk_ba7besh_b', 'business_working_hours', type_='foreignkey')
    op.create_foreign_key(None, 'business_working_hours', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('category', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category', 'parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ba7besh_category_parent_id_3d658cb9', table_name='category')
    op.drop_index('ba7besh_category_slug_613193a1_like', table_name='category')
    op.drop_constraint('ba7besh_category_parent_id_3d658cb9_fk_ba7besh_category_id', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('feature', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('feature', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ba7besh_feature_category_id_b8467211', table_name='feature')
    op.drop_constraint('ba7besh_feature_category_id_b8467211_fk_ba7besh_category_id', 'feature', type_='foreignkey')
    op.create_foreign_key(None, 'feature', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('features_category', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('features_category', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.create_foreign_key('ba7besh_feature_category_id_b8467211_fk_ba7besh_category_id', 'feature', 'category', ['category_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_feature_category_id_b8467211', 'feature', ['category_id'], unique=False)
    op.alter_column('feature', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('feature', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('ba7besh_category_parent_id_3d658cb9_fk_ba7besh_category_id', 'category', 'category', ['parent_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_category_slug_613193a1_like', 'category', ['slug'], unique=False)
    op.create_index('ba7besh_category_parent_id_3d658cb9', 'category', ['parent_id'], unique=False)
    op.alter_column('category', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('category', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'business_working_hours', type_='foreignkey')
    op.create_foreign_key('ba7besh_businesswork_business_id_8a81eaf1_fk_ba7besh_b', 'business_working_hours', 'business', ['business_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_unique_constraint('unique_business_day', 'business_working_hours', ['business_id', 'day'])
    op.create_index('ba7besh_businessworkinghours_business_id_8a81eaf1', 'business_working_hours', ['business_id'], unique=False)
    op.alter_column('business_working_hours', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_working_hours', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'business_tags', type_='foreignkey')
    op.create_foreign_key('ba7besh_businesstags_business_id_cb68436c_fk_ba7besh_b', 'business_tags', 'business', ['business_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_businesstags_business_id_cb68436c', 'business_tags', ['business_id'], unique=False)
    op.alter_column('business_tags', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_tags', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'business_features', type_='foreignkey')
    op.drop_constraint(None, 'business_features', type_='foreignkey')
    op.create_foreign_key('ba7besh_businessfeat_feature_id_bc4dac42_fk_ba7besh_f', 'business_features', 'feature', ['feature_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('ba7besh_businessfeat_business_id_14cddcb8_fk_ba7besh_b', 'business_features', 'business', ['business_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_businessfeatures_feature_id_bc4dac42', 'business_features', ['feature_id'], unique=False)
    op.create_index('ba7besh_businessfeatures_business_id_14cddcb8', 'business_features', ['business_id'], unique=False)
    op.alter_column('business_features', 'feature_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_features', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_features', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'business_contacts', type_='foreignkey')
    op.create_foreign_key('ba7besh_businesscont_business_id_15cf0080_fk_ba7besh_b', 'business_contacts', 'business', ['business_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_businesscontacts_business_id_15cf0080', 'business_contacts', ['business_id'], unique=False)
    op.alter_column('business_contacts', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_contacts', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'business_categories', type_='foreignkey')
    op.drop_constraint(None, 'business_categories', type_='foreignkey')
    op.create_foreign_key('ba7besh_businesscate_business_id_e4b002d4_fk_ba7besh_b', 'business_categories', 'business', ['business_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('ba7besh_businesscate_category_id_535d71ee_fk_ba7besh_c', 'business_categories', 'category', ['category_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ba7besh_businesscategories_category_id_535d71ee', 'business_categories', ['category_id'], unique=False)
    op.create_index('ba7besh_businesscategories_business_id_e4b002d4', 'business_categories', ['business_id'], unique=False)
    op.alter_column('business_categories', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_categories', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('business_categories', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_business_location', table_name='business', postgresql_using='gist')
    op.alter_column('business', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('business', 'address_line2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('business', 'address_line1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('business', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('socialaccount_socialaccount',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='socialaccount_socialaccount_pkey'),
    sa.UniqueConstraint('provider', 'uid', name='socialaccount_socialaccount_provider_uid_fc810c6e_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('socialaccount_socialaccount_user_id_8146e70c', 'socialaccount_socialaccount', ['user_id'], unique=False)
    op.create_table('account_emailconfirmation',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sent', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email_address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_address_id'], ['account_emailaddress.id'], name='account_emailconfirm_email_address_id_5b7f8c58_fk_account_e', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='account_emailconfirmation_pkey'),
    sa.UniqueConstraint('key', name='account_emailconfirmation_key_key')
    )
    op.create_index('account_emailconfirmation_key_f43612bd_like', 'account_emailconfirmation', ['key'], unique=False)
    op.create_index('account_emailconfirmation_email_address_id_5b7f8c58', 'account_emailconfirmation', ['email_address_id'], unique=False)
    op.create_table('oauth2_provider_grant',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('redirect_uri', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('code_challenge', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('code_challenge_method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nonce', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('claims', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['oauth2_provider_application.id'], name='oauth2_provider_gran_application_id_81923564_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='oauth2_provider_grant_pkey'),
    sa.UniqueConstraint('code', name='oauth2_provider_grant_code_key')
    )
    op.create_index('oauth2_provider_grant_user_id_e8f62af8', 'oauth2_provider_grant', ['user_id'], unique=False)
    op.create_index('oauth2_provider_grant_code_49ab4ddf_like', 'oauth2_provider_grant', ['code'], unique=False)
    op.create_index('oauth2_provider_grant_application_id_81923564', 'oauth2_provider_grant', ['application_id'], unique=False)
    op.create_table('social_auth_partial',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('next_step', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('backend', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('next_step >= 0', name='social_auth_partial_next_step_check'),
    sa.PrimaryKeyConstraint('id', name='social_auth_partial_pkey')
    )
    op.create_index('social_auth_partial_token_3017fea3_like', 'social_auth_partial', ['token'], unique=False)
    op.create_index('social_auth_partial_token_3017fea3', 'social_auth_partial', ['token'], unique=False)
    op.create_index('social_auth_partial_timestamp_50f2119f', 'social_auth_partial', ['timestamp'], unique=False)
    op.create_table('account_emailaddress',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='account_emailaddress_user_id_2c513194_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='account_emailaddress_pkey'),
    sa.UniqueConstraint('email', name='account_emailaddress_email_key')
    )
    op.create_index('account_emailaddress_user_id_2c513194', 'account_emailaddress', ['user_id'], unique=False)
    op.create_index('account_emailaddress_email_03be32b2_like', 'account_emailaddress', ['email'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('social_auth_code',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_code_pkey'),
    sa.UniqueConstraint('email', 'code', name='social_auth_code_email_code_801b2d02_uniq')
    )
    op.create_index('social_auth_code_timestamp_176b341f', 'social_auth_code', ['timestamp'], unique=False)
    op.create_index('social_auth_code_code_a2393167_like', 'social_auth_code', ['code'], unique=False)
    op.create_index('social_auth_code_code_a2393167', 'social_auth_code', ['code'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('socialaccount_socialtoken',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['socialaccount_socialaccount.id'], name='socialaccount_social_account_id_951f210e_fk_socialacc', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['app_id'], ['socialaccount_socialapp.id'], name='socialaccount_social_app_id_636a42d7_fk_socialacc', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='socialaccount_socialtoken_pkey'),
    sa.UniqueConstraint('app_id', 'account_id', name='socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq')
    )
    op.create_index('socialaccount_socialtoken_app_id_636a42d7', 'socialaccount_socialtoken', ['app_id'], unique=False)
    op.create_index('socialaccount_socialtoken_account_id_951f210e', 'socialaccount_socialtoken', ['account_id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('temp_business',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('street', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('beeorder_registed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('open_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('close_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_delivery', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_delivery_distance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asap_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cuisine', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_estimation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_image_url', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('oauth2_provider_idtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('jti', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['oauth2_provider_application.id'], name='oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='oauth2_provider_idtoken_user_id_dd512b59_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='oauth2_provider_idtoken_pkey'),
    sa.UniqueConstraint('jti', name='oauth2_provider_idtoken_jti_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oauth2_provider_idtoken_user_id_dd512b59', 'oauth2_provider_idtoken', ['user_id'], unique=False)
    op.create_index('oauth2_provider_idtoken_application_id_08c5ff4f', 'oauth2_provider_idtoken', ['application_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('social_auth_usersocialauth',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='social_auth_usersocialauth_pkey'),
    sa.UniqueConstraint('provider', 'uid', name='social_auth_usersocialauth_provider_uid_e6b5e668_uniq')
    )
    op.create_index('social_auth_usersocialauth_user_id_17d28448', 'social_auth_usersocialauth', ['user_id'], unique=False)
    op.create_index('social_auth_usersocialauth_uid_796e51dc_like', 'social_auth_usersocialauth', ['uid'], unique=False)
    op.create_index('social_auth_usersocialauth_uid_796e51dc', 'social_auth_usersocialauth', ['uid'], unique=False)
    op.create_table('django_site',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_site_pkey'),
    sa.UniqueConstraint('domain', name='django_site_domain_a2e37b91_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('django_site_domain_a2e37b91_like', 'django_site', ['domain'], unique=False)
    op.create_table('social_auth_association',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('issued', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lifetime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assoc_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_association_pkey'),
    sa.UniqueConstraint('server_url', 'handle', name='social_auth_association_server_url_handle_078befa2_uniq')
    )
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    sa.UniqueConstraint('name', name='topology_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('social_auth_nonce',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(length=65), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_nonce_pkey'),
    sa.UniqueConstraint('server_url', 'timestamp', 'salt', name='social_auth_nonce_server_url_timestamp_salt_f6284463_uniq')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('socialaccount_socialapp_sites',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('socialapp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['django_site.id'], name='socialaccount_social_site_id_2579dee5_fk_django_si', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['socialapp_id'], ['socialaccount_socialapp.id'], name='socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='socialaccount_socialapp_sites_pkey'),
    sa.UniqueConstraint('socialapp_id', 'site_id', name='socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq')
    )
    op.create_index('socialaccount_socialapp_sites_socialapp_id_97fb6e7d', 'socialaccount_socialapp_sites', ['socialapp_id'], unique=False)
    op.create_index('socialaccount_socialapp_sites_site_id_2579dee5', 'socialaccount_socialapp_sites', ['site_id'], unique=False)
    op.create_table('oauth2_provider_application',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('redirect_uris', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('authorization_grant_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('client_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skip_authorization', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('post_logout_redirect_uris', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='oauth2_provider_application_user_id_79829054_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='oauth2_provider_application_pkey'),
    sa.UniqueConstraint('client_id', name='oauth2_provider_application_client_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oauth2_provider_application_user_id_79829054', 'oauth2_provider_application', ['user_id'], unique=False)
    op.create_index('oauth2_provider_application_client_secret_53133678_like', 'oauth2_provider_application', ['client_secret'], unique=False)
    op.create_index('oauth2_provider_application_client_secret_53133678', 'oauth2_provider_application', ['client_secret'], unique=False)
    op.create_index('oauth2_provider_application_client_id_03f0cc84_like', 'oauth2_provider_application', ['client_id'], unique=False)
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name='layer_topology_id_fkey'),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key')
    )
    op.create_table('socialaccount_socialapp',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='socialaccount_socialapp_pkey')
    )
    op.create_table('oauth2_provider_refreshtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('access_token_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['access_token_id'], ['oauth2_provider_accesstoken.id'], name='oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['application_id'], ['oauth2_provider_application.id'], name='oauth2_provider_refr_application_id_2d1c311b_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='oauth2_provider_refreshtoken_pkey'),
    sa.UniqueConstraint('access_token_id', name='oauth2_provider_refreshtoken_access_token_id_key'),
    sa.UniqueConstraint('token', 'revoked', name='oauth2_provider_refreshtoken_token_revoked_af8a5134_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oauth2_provider_refreshtoken_user_id_da837fce', 'oauth2_provider_refreshtoken', ['user_id'], unique=False)
    op.create_index('oauth2_provider_refreshtoken_application_id_2d1c311b', 'oauth2_provider_refreshtoken', ['application_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('temp_business_movo',
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('res_full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('res_full_name_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('res_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('res_category_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('com_header', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_img', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('on_top', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('com_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Column1.delivery_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_types', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lon', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pre_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('close_pre_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('working', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('menu_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('res_msg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('es_msg_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('res_msg_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('branch_area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('branch_area_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('busy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('close_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friday_close', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prepare_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_kilo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cash', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fatora', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mtn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('epay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('delivery_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_charge_movo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_punch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('punchPrice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('punch_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isLoyalityCard', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('close_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('oauth2_provider_accesstoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source_refresh_token_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_token_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['oauth2_provider_application.id'], name='oauth2_provider_acce_application_id_b22886e1_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['id_token_id'], ['oauth2_provider_idtoken.id'], name='oauth2_provider_acce_id_token_id_85db651b_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['source_refresh_token_id'], ['oauth2_provider_refreshtoken.id'], name='oauth2_provider_acce_source_refresh_token_e66fbc72_fk_oauth2_pr', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='oauth2_provider_accesstoken_user_id_6e4c9a65_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='oauth2_provider_accesstoken_pkey'),
    sa.UniqueConstraint('id_token_id', name='oauth2_provider_accesstoken_id_token_id_key'),
    sa.UniqueConstraint('source_refresh_token_id', name='oauth2_provider_accesstoken_source_refresh_token_id_key'),
    sa.UniqueConstraint('token', name='oauth2_provider_accesstoken_token_key')
    )
    op.create_index('oauth2_provider_accesstoken_user_id_6e4c9a65', 'oauth2_provider_accesstoken', ['user_id'], unique=False)
    op.create_index('oauth2_provider_accesstoken_token_8af090f8_like', 'oauth2_provider_accesstoken', ['token'], unique=False)
    op.create_index('oauth2_provider_accesstoken_application_id_b22886e1', 'oauth2_provider_accesstoken', ['application_id'], unique=False)
    # ### end Alembic commands ###
