name: "Check, Build"

on:
    push:
        branches: [develop]
        tags: [v*]
    pull_request:
        types: [opened, synchronize]
  
jobs:
  format-check:
    name: "Format Check"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --with dev
    
      - name: Import Order Check with isort
        if: always()
        run: |
            poetry run isort --check-only --diff --verbose ./src/app
            poetry run isort --check-only --diff --verbose ./src/core

      - name: autopep8 core
        id: autopep8-core
        uses: peter-evans/autopep8@v2
        with:
          args: ./src/core --recursive --in-place

      - name: autopep8 ape
        id: autopep8-app
        uses: peter-evans/autopep8@v2
        with:
          args: ./src/app --recursive --in-place

  check-lint:
    name: "Check Linting"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --with dev
    
      - name: Lint - ruff
        id: lint
        if: always()
        run: |
            poetry run ruff ./src/app/ 
            poetry run ruff ./src/core/ 

  check-utils-types:
    name: "Check Utils Types"
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --with dev

      - name: Type Check - mypy
        run: |
          poetry run mypy ./src/app
          poetry run mypy ./src/core
