name: "Check, Build"

on:
    push:
        branches: [develop]
        tags: [v*]
    pull_request:
        types: [opened, synchronize]

jobs:
  format-check:
    name: "Format Check"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Run format command
        if: always()
        run: |
            poetry format

  check-lint:
    name: "Check Linting"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Lint - ruff
        id: lint
        if: always()
        run: |
            poetry run ruff src
            poetry run ruff tests

  check-utils-types:
    name: "Check Utils Types"
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Type Check - mypy
        run: |
          poetry lint
